### ISSUE TITLE
SOLID 적용

### ISSUE THREAD

**Issue by middlefitting** [middlefitting/SpringBasicWebProject#14]
### 제안 사항
코드의 설계가 현재의 시점으로 봤을때 많이 부족한 상황입니다. 기능 개발에 앞서 SOLID 원칙에 따라 코드를 재정비합니다. 

### Todo
컨트롤러 역할 분리
- [ ] 테스트 코드 configService 의존성 제거
- [ ] HTTP 요청 처리 별도 클래스 분할
- [ ] 비즈니스 로직 호출 별도 클래스 분할
- [ ] HTTP 응답 생성 별도 클래스 분할
- [ ] 예외 처리 별도 클래스 분할
